name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      # This is needed because lerna expects loom-common to be an npm package (which it only is if it has a package.json file)
      # Normally, this is done as part of the build process, but it also needs to be done for a fresh install.
      - name: Setup loom-common
      - run: mkdir -p loom-common/out && cp loom-common/package.json loom-common/out

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm run test
